### ISSUE TITLE
Events not picked up

### ISSUE THREAD

**Issue by alxpl** [fedora-infra/fedmsg#397] opened 2017-02-01 09:36 UTC
Some time ago I noticed I was missing some badges, which should have been awarded automatically:
https://github.com/fedora-infra/tahrir/issues/318
https://github.com/fedora-infra/tahrir/issues/349

While looking at the dates when these should have been triggered, I noticed that Datagrepper did not display the activities in question and I filed a bug against it.:
https://github.com/fedora-infra/datagrepper/issues/183

It just hit me that I should have reported the bug here.

**Comment by jeremycline** [comment] 2017-06-14 12:45
Hey @alxpl,

fedmsg uses ZeroMQ with publish/subscribe sockets. This configuration does not guarantee message delivery since the publisher doesn't really care if anyone is subscribed or not. This means messages will get missed when various services restart or there's a network partition. That doesn't mean there *isn't* a bug in fedmsg that causes extra messages to be missed, but without a solid reproducer it's difficult or impossible to say whether this is a bug or not.

Given that, I'm going to close this, but thank you for investigating this and taking the time to report it!

**Closed by jeremycline** 2017-06-14 12:45 UTC
